#!/bin/bash

# Submit all full retraining jobs (step 2) — one job per feature per dataset.
# Configs are generated by 1.1_TuneResultExtraction.py into configs/<dataset>/retrain/.

# NoXi-base
sbatch run_2_full_trainer.slurm configs/noxi-base/retrain/audio.egemapsv2.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-base/retrain/clip.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-base/retrain/openpose.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-base/retrain/audio.w2vbert2_embeddings.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-base/retrain/xlm_roberta_embeddings.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-base/retrain/openface2.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-base/retrain/openface3.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-base/retrain/dino.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-base/retrain/swin.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-base/retrain/videomae.stream.json

# NoXi-J
sbatch run_2_full_trainer.slurm configs/noxi-j/retrain/audio.egemapsv2.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-j/retrain/clip.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-j/retrain/openpose.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-j/retrain/audio.w2vbert2_embeddings.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-j/retrain/xlm_roberta_embeddings.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-j/retrain/openface2.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-j/retrain/openface3.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-j/retrain/dino.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-j/retrain/swin.stream.json
sbatch run_2_full_trainer.slurm configs/noxi-j/retrain/videomae.stream.json

# PInSoRo-CC
sbatch run_2_full_trainer.slurm configs/pinsoro-cc/retrain/audio.egemapsv2.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cc/retrain/clip.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cc/retrain/openpose.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cc/retrain/audio.w2vbert2_embeddings.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cc/retrain/xlm_roberta_embeddings.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cc/retrain/openface2.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cc/retrain/openface3.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cc/retrain/dino.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cc/retrain/swin.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cc/retrain/videomae.stream.json

# PInSoRo-CR
sbatch run_2_full_trainer.slurm configs/pinsoro-cr/retrain/audio.egemapsv2.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cr/retrain/clip.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cr/retrain/openpose.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cr/retrain/audio.w2vbert2_embeddings.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cr/retrain/xlm_roberta_embeddings.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cr/retrain/openface2.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cr/retrain/openface3.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cr/retrain/dino.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cr/retrain/swin.stream.json
sbatch run_2_full_trainer.slurm configs/pinsoro-cr/retrain/videomae.stream.json
